"""
Runs the real `run-playwright` tool as a child process and tracks it for the web UI.

Everything the UI sends is validated here (not just in the browser):
terms accepted, safe folder name, safe paths.
Passwords go to the child process through environment variables, never on the command line.
"""

import csv
import json
import os
import re
import signal
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path
from urllib.parse import urlparse

from qa_generator import legal
from qa_generator.cli import WORKSPACE_DIR, output_dir_is_safe
from qa_generator.utils import slugify

ROOT = Path(__file__).resolve().parent.parent.parent
ENTRY = ROOT / "run_playwright.py"

MODES = ("all", "e2e", "api")
SUITE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$")
WINDOWS_RESERVED = {"con", "prn", "aux", "nul", *(f"com{i}" for i in range(1, 10)), *(f"lpt{i}" for i in range(1, 10))}
URL_PATH = re.compile(r"^/[\w\-./~%]{0,200}$")
MAX_LINES = 20000
HISTORY_LIMIT = 200
PASSWORD_ENV = {"user": "QA_USER_PASSWORD", "admin": "QA_ADMIN_PASSWORD"}


class RequestError(Exception):
    def __init__(self, status: int, code: str, message: str):
        super().__init__(message)
        self.status, self.code, self.message = status, code, message


# ---------------------------------------------------------------------------
# Request validation
# ---------------------------------------------------------------------------
def _path(value, field: str) -> str:
    value = str(value or "").strip()
    if not value:
        return ""
    value = "/" + value.lstrip("/")
    if not URL_PATH.match(value):
        raise RequestError(400, "bad_path", f"'{field}' contains characters that are not allowed in a URL path.")
    return value


def build_command(body: dict):
    """Validate the UI request. Returns (argv, extra_env, secrets, info). Raises RequestError."""
    if not isinstance(body, dict):
        raise RequestError(400, "bad_request", "Expected a JSON object.")

    url = str(body.get("url", "")).strip()
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.hostname or len(url) > 2048 or any(c.isspace() for c in url):
        raise RequestError(400, "bad_url", "Enter a valid http(s) address, for example https://example.com.")
    host = parsed.hostname.lower()

    mode = body.get("mode")
    if mode not in MODES:
        raise RequestError(400, "bad_mode", "Mode must be one of: " + ", ".join(MODES))

    suite = str(body.get("suiteName") or "").strip() or slugify(host)
    if not SUITE_NAME.match(suite) or suite.lower() in WINDOWS_RESERVED:
        raise RequestError(400, "bad_suite_name", "Suite name: letters, numbers, '-' and '_' only (max 64), starting with a letter or number.")
    suite_dir = (WORKSPACE_DIR / suite).resolve()
    if suite_dir.parent != WORKSPACE_DIR.resolve():
        raise RequestError(400, "bad_suite_name", "Suite name must be a plain folder name.")
    if not output_dir_is_safe(suite_dir):
        raise RequestError(409, "folder_exists", f"'{suite}' already exists and was not generated by this tool. Choose another suite name.")

    # Terms must be accepted before anything runs (checked again by the CLI).
    if not legal.has_accepted_terms():
        raise RequestError(403, "terms_required", "Accept the Terms of Use and Privacy Notice first.")
    argv = [sys.executable, "-u", str(ENTRY), url, "--mode", mode, "-o", suite]

    extra_env, secrets = {}, []
    auth = body.get("auth") or {}
    users = {}
    for u in auth.get("users") or []:
        kind = u.get("kind")
        if kind in PASSWORD_ENV and kind not in users and str(u.get("identifier", "")).strip():
            users[kind] = u
    if auth.get("enabled") and users:
        login = _path(auth.get("loginPath"), "login path")
        if login:
            argv.append(f"--login-url={login}")
        for kind, u in users.items():
            password = str(u.get("password") or "")
            if not password:
                raise RequestError(400, "missing_password", f"Enter the password for '{u['identifier']}', or turn authentication off.")
            flag = "--user" if kind == "user" else "--admin-user"
            argv.append(f"{flag}={str(u['identifier']).strip()}")
            extra_env[PASSWORD_ENV[kind]] = password
            if len(password) >= 3:
                secrets.append(password)
        redirect = _path(auth.get("redirectPath"), "redirect path")
        if redirect and "user" in users:
            argv.append(f"--user-target={redirect}")
    else:
        argv.append("--no-auth")
    if body.get("headed"):
        argv.append("--headed")
    if body.get("writeTests") and mode in ("all", "api"):
        argv.append("--include-write-tests")
    if body.get("submitForms") and mode in ("all", "e2e"):
        argv.append("--submit-forms")
    try:
        timeout = int(body.get("timeoutMs") or 30000)
    except (TypeError, ValueError):
        raise RequestError(400, "bad_timeout", "Timeout must be a number of milliseconds.")
    if not 1000 <= timeout <= 300000:
        raise RequestError(400, "bad_timeout", "Timeout must be between 1000 and 300000 ms.")
    if timeout != 30000:
        argv.append(f"--timeout={timeout}")

    return argv, extra_env, secrets, {"url": url, "host": host, "mode": mode, "suite": suite, "suite_dir": suite_dir}


# ---------------------------------------------------------------------------
# A single run
# ---------------------------------------------------------------------------
STAGE_TITLES = ("Dynamic Crawl & Discovery", "Suite Code Generation", "Pytest & Playwright Runner")
RE_STAGE = re.compile(r"^\[(\d)/4\]")
RE_COLLECTED = re.compile(r"collected (\d+) items?")
RE_TEST = re.compile(r"\b(PASSED|FAILED|ERROR|SKIPPED)\b\s+\[\s*(\d+)%\]")
RE_GENERATED = re.compile(r"Generated (\d+) tailored test files")
RE_SUMMARY = re.compile(r"^\s+- (Navigation Routes|Same-site API calls)\s*:\s*(\d+)")


class Run:
    def __init__(self, info: dict, secrets: list):
        self.id = uuid.uuid4().hex[:12]
        self.info, self.secrets = info, secrets
        self.status = "running"
        self.exit_code = None
        self.started_at = time.time()
        self.finished_at = None
        self.lines, self.offset = [], 0
        self.stage = 0
        self.total = self.percent = 0
        self.counts = {"PASSED": 0, "FAILED": 0, "SKIPPED": 0, "ERROR": 0}
        self.details = {}
        self.cancelled = False
        self.proc = None
        self.lock = threading.Lock()

    def add_line(self, line: str):
        for secret in self.secrets:
            line = line.replace(secret, "***")
        with self.lock:
            self.lines.append(line)
            if len(self.lines) > MAX_LINES:
                del self.lines[:5000]
                self.offset += 5000
            if m := RE_STAGE.match(line):
                self.stage = int(m.group(1))
            elif m := RE_COLLECTED.search(line):
                self.total = int(m.group(1))
            elif m := RE_TEST.search(line):
                self.counts[m.group(1)] += 1
                self.percent = int(m.group(2))
            elif m := RE_GENERATED.search(line):
                self.details["generated"] = int(m.group(1))
            elif m := RE_SUMMARY.match(line):
                self.details[m.group(1)] = int(m.group(2))

    def stages(self):
        def state(n):
            if self.status != "running" and self.stage < n:
                return "pending"
            return "done" if self.stage > n or (n == 3 and self.stage == 4) else ("running" if self.stage == n else "pending")

        d = self.details
        crawl = f"{d.get('Navigation Routes', 0)} routes / {d.get('Same-site API calls', 0)} API calls" if self.stage > 1 else "Scanning the site..."
        gen = f"Generated {d['generated']} test files" if "generated" in d else "Waiting"
        done = sum(self.counts.values())
        tests = f"{done}/{self.total} tests" if self.total else "Waiting"
        return [
            {"title": f"1. {STAGE_TITLES[0]}", "state": state(1), "detail": crawl},
            {"title": f"2. {STAGE_TITLES[1]}", "state": state(2), "detail": gen},
            {"title": f"3. {STAGE_TITLES[2]}", "state": state(3), "detail": tests},
        ]

    def snapshot(self, after: int = 0):
        with self.lock:
            start = max(0, after - self.offset)
            end = self.finished_at or time.time()
            return {
                "id": self.id, "url": self.info["url"], "mode": self.info["mode"], "suite": self.info["suite"],
                "suiteDir": str(self.info["suite_dir"]), "status": self.status, "exitCode": self.exit_code,
                "elapsedSec": round(end - self.started_at, 1), "percent": 100 if self.status != "running" and self.total else self.percent,
                "counts": {"passed": self.counts["PASSED"], "failed": self.counts["FAILED"] + self.counts["ERROR"],
                           "skipped": self.counts["SKIPPED"], "total": self.total},
                "stages": self.stages(), "lines": self.lines[start:], "next": self.offset + len(self.lines),
            }


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------
class RunManager:
    def __init__(self):
        self.runs, self.lock = {}, threading.Lock()
        self.current = None

    # -- history (no secrets: ids, targets, outcome) --
    def _history_file(self) -> Path:
        return legal.config_dir() / "runs.json"

    def history(self):
        try:
            return json.loads(self._history_file().read_text(encoding="utf-8"))
        except Exception:
            return []

    def _save_history(self, run: Run):
        snap = run.snapshot()
        entry = {"id": run.id, "url": snap["url"], "mode": snap["mode"], "suite": snap["suite"], "status": snap["status"],
                 "startedAt": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(run.started_at)), "elapsedSec": snap["elapsedSec"],
                 **snap["counts"]}
        data = (self.history() + [entry])[-HISTORY_LIMIT:]
        try:
            self._history_file().parent.mkdir(parents=True, exist_ok=True)
            self._history_file().write_text(json.dumps(data, indent=1), encoding="utf-8")
        except OSError:
            pass

    # -- lifecycle --
    def start(self, body: dict) -> Run:
        argv, extra_env, secrets, info = build_command(body)
        with self.lock:
            if self.current and self.current.status == "running":
                raise RequestError(409, "busy", "A run is already in progress. Stop it or wait for it to finish.")
            env = {k: v for k, v in os.environ.items() if k not in PASSWORD_ENV.values()}
            env.update(extra_env, PYTHONUNBUFFERED="1", PYTHONUTF8="1", PYTHONIOENCODING="utf-8",
                       QA_GENERATOR_WORKSPACE=str(WORKSPACE_DIR))
            flags = {}
            if os.name == "nt":
                flags["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.CREATE_NO_WINDOW
            else:
                flags["start_new_session"] = True
            run = Run(info, secrets)
            run.proc = subprocess.Popen(argv, cwd=ROOT, env=env, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                                        stderr=subprocess.STDOUT, **flags)
            self.runs[run.id] = run
            self.current = run
        threading.Thread(target=self._pump, args=(run,), daemon=True).start()
        return run

    def _pump(self, run: Run):
        try:
            for raw in run.proc.stdout:
                run.add_line(raw.decode("utf-8", "replace").rstrip("\r\n"))
        finally:
            code = run.proc.wait()
            with run.lock:
                run.exit_code, run.finished_at = code, time.time()
                run.status = ("cancelled" if run.cancelled else "passed" if code == 0 else "failed" if code == 1
                              else "blocked" if code == 2 else "error")
                if run.status == "passed" and run.stage == 3:
                    run.stage = 4
            self._save_history(run)

    def get(self, run_id: str) -> Run:
        run = self.runs.get(run_id)
        if not run:
            raise RequestError(404, "no_such_run", "Unknown run.")
        return run

    def cancel(self, run_id: str):
        run = self.get(run_id)
        if run.status != "running":
            return
        run.cancelled = True
        kill_tree(run.proc)

    def shutdown(self):
        if self.current and self.current.status == "running":
            self.current.cancelled = True
            kill_tree(self.current.proc)

    # -- results --
    def results(self, run_id: str) -> dict:
        run = self.get(run_id)
        suite_dir = Path(run.info["suite_dir"])
        rows, scan = [], {}
        csv_file = suite_dir / "reports" / "latest_test_run.csv"
        if run.status != "running" and csv_file.is_file():
            with open(csv_file, encoding="utf-8-sig", newline="") as f:
                rows = list(csv.DictReader(f))[:2000]
        try:
            scan = json.loads((suite_dir / "scan.json").read_text(encoding="utf-8"))
        except (OSError, ValueError):
            pass
        return {"rows": rows, "routes": routes_from_scan(scan), "chips": chips_from_scan(scan),
                "reportPath": str(suite_dir / "reports" / "index.html") if rows else None}


def kill_tree(proc: subprocess.Popen):
    """Stop the child and everything it started (pytest, browsers)."""
    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"], capture_output=True, timeout=15)
        else:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
    except Exception:
        try:
            proc.kill()
        except Exception:
            pass


def routes_from_scan(scan: dict) -> list:
    rows = []
    for lk in (scan.get("homepage") or {}).get("nav_links", []):
        ctype = (lk.get("content_type") or "").split(";")[0]
        rows.append({"method": "GET", "path": lk.get("route", "/"), "status": lk.get("status"), "meta": [ctype] if ctype else []})
    for api in scan.get("captured_apis", []):
        meta = [f"{len(api['sample_keys'])} JSON keys"] if api.get("sample_keys") else []
        rows.append({"method": api.get("method", "GET"), "path": api.get("path", ""), "status": api.get("status"), "meta": meta})
    return rows[:500]


def chips_from_scan(scan: dict) -> list:
    c = scan.get("components") or {}
    out = []
    for icon, n, label in (("edit_note", len(c.get("forms") or []), "Forms"), ("dashboard_customize", len(c.get("all_cards") or []), "Card groups"),
                           ("travel_explore", 1 if c.get("search") else 0, "Search"), ("picture_in_picture", 1 if c.get("modal") else 0, "Modals"),
                           ("table_chart", len(c.get("tables") or []), "Tables"), ("filter_alt", len(c.get("filters") or []), "Filters")):
        if n:
            out.append({"icon": icon, "label": f"{n} {label}"})
    return out
