"""
Writers for tests/e2e/*.py (browser tests).

Rule for every generated test: if the scan found something, the test asserts it
hard. Nothing is wrapped in "if it exists" — a missing element is a failure.
Templates use __TOKEN__ placeholders (filled with Python literals via py()) so
the test code below reads like normal Python.
"""

from urllib.parse import urlparse

from qa_generator.config import MAX_E2E_ROUTE_TESTS, TABLE_SELECTOR
from qa_generator.generator.context import SuiteContext
from qa_generator.scanner.components import _visible_variant
from qa_generator.scanner.standalone import PROBE
from qa_generator.templates.qa_login import is_login_url
from qa_generator.utils import UniqueNamer, css_attr, path_of, py, same_site


def fill(template: str, **values) -> str:
    for key, value in values.items():
        template = template.replace(f"__{key}__", py(value))
    return template


def header(doc: str, ctx: SuiteContext, imports: str, markers: str) -> str:
    return (
        f'"""\n{doc}\n\nGenerated by Nes-Dev QA from a live scan of {ctx.target_url}\n"""\n\n'
        f"{imports}\n\npytestmark = {markers}\n"
    )


PAGE_IMPORTS = "import re\n\nimport pytest\nfrom playwright.sync_api import Page, expect\n\nfrom qa_forms import text_re"
AUTH_IMPORTS = PAGE_IMPORTS + "\n\nfrom qa_login import LOGOUT_SELECTOR, access_blocked, is_login_url, password_field_visible"


FORM_IMPORTS = ("\n\nfrom qa_forms import (SUBMIT_BUTTON, check_empty_submit, check_valid_submit,\n"
                "                      fill_form, submit_and_observe)")


def write_e2e_tests(ctx: SuiteContext) -> None:
    write_navigation(ctx)
    write_components(ctx)
    write_interactions(ctx)
    write_accessibility(ctx)
    write_forms(ctx)
    write_user_session(ctx)
    write_admin_portal(ctx)
    write_access_control(ctx)


# ---------------------------------------------------------------------------
# test_navigation.py
# ---------------------------------------------------------------------------
def write_navigation(ctx: SuiteContext) -> None:
    hp = ctx.scan["homepage"]
    # Browser tests only visit links that served an HTML page to a guest during the scan
    # (no auth-protected pages, no file downloads).
    links = [lk for lk in hp.get("nav_links", []) if _is_guest_html_page(lk)]
    code = header("Homepage, navigation links, public pages, mobile layout and console errors.",
                  ctx, PAGE_IMPORTS, "pytest.mark.e2e")

    title = hp.get("title", "")
    title_snippet = title.split(" - ")[0].split("|")[0].strip() or title.strip()
    code += fill('''

@pytest.mark.smoke
def test_homepage_title_and_hero(page: Page, base_url: str):
    """Verify the homepage loads with its title and main heading."""
    response = page.goto(base_url)
    assert response is not None and response.status < 400, f"Homepage returned {response.status if response else 'no response'}"
''')
    if title_snippet:
        code += fill('''    expect(page).to_have_title(re.compile(re.escape(__T__), re.IGNORECASE))
''', T=title_snippet)
    if hp.get("heading"):
        code += '''    expect(page.locator("h1, [role='heading'][aria-level='1'], h2").first).to_be_visible()
'''

    # Primary call-to-action
    cta = hp.get("primary_cta")
    if cta and not cta.get("new_tab"):
        sel = cta["selector"] + ":visible"
        if same_site(cta["full_url"], ctx.target_url) and (urlparse(cta["full_url"]).path or "/") not in ("", "/"):
            code += fill('''

def test_primary_cta_navigates(page: Page, base_url: str):
    """Verify the primary call-to-action button opens its target page."""
    page.goto(base_url)
    cta = page.locator(__SEL__).first
    expect(cta).to_be_visible()
    cta.click()
    expect(page).to_have_url(re.compile(re.escape(__PATH__)))
''', SEL=sel, PATH=urlparse(cta["full_url"]).path)
        else:
            code += fill('''

def test_primary_cta_visible(page: Page, base_url: str):
    """Verify the primary call-to-action button is shown."""
    page.goto(base_url)
    expect(page.locator(__SEL__).first).to_be_visible()
''', SEL=sel)

    # Skip link (accessibility)
    skip = hp.get("skip_link")
    if skip:
        code += fill('''

def test_skip_link_target_exists(page: Page, base_url: str):
    """Verify the skip-to-content link points at an element that exists."""
    page.goto(base_url)
    expect(page.locator(__LINK__).first).to_be_attached()
    expect(page.locator(__TARGET__).first).to_be_attached()
''', LINK=f"a{css_attr('href', skip['href'])}",
            TARGET=f"{css_attr('id', skip['target_id'])}, a{css_attr('name', skip['target_id'])}")

    # Clickable, visible navigation links
    namer = UniqueNamer()
    clicks = [
        (namer(lk["name"], "link"), f"a{css_attr('href', lk['href'])}:visible", lk["route"])
        for lk in links
        if lk.get("href") and lk.get("visible") and not lk.get("new_tab") and lk["route"] not in ("", "/")
    ][:MAX_E2E_ROUTE_TESTS]
    if clicks:
        code += fill('''

NAV_CLICKS = __CLICKS__


@pytest.mark.parametrize("selector, route", [c[1:] for c in NAV_CLICKS], ids=[c[0] for c in NAV_CLICKS])
def test_nav_link_navigates(page: Page, base_url: str, selector: str, route: str):
    """Verify clicking a navigation link opens its page."""
    page.goto(base_url)
    link = page.locator(selector).first
    expect(link).to_be_visible()
    link.click()
    expect(page).to_have_url(re.compile(re.escape(route)))
''', CLICKS=clicks)

    # Public pages load
    namer = UniqueNamer()
    routes = [(namer(lk["name"], "page"), lk["full_url"]) for lk in links][:MAX_E2E_ROUTE_TESTS]
    if routes:
        code += fill('''

PUBLIC_PAGES = __ROUTES__


@pytest.mark.parametrize("url", [p[1] for p in PUBLIC_PAGES], ids=[p[0] for p in PUBLIC_PAGES])
def test_public_route_loads(page: Page, url: str):
    """Verify a public page loads without an error status."""
    response = page.goto(url)
    assert response is not None and response.status < 400, f"{url} returned {response.status if response else 'no response'}"
    expect(page.locator("body")).to_be_visible()
''', ROUTES=routes)

    code += '''

def test_mobile_responsive_layout(page: Page, base_url: str):
    """Verify the homepage fits a 375px mobile screen without horizontal scrolling."""
    page.set_viewport_size({"width": 375, "height": 667})
    page.goto(base_url)
    expect(page.locator("body")).to_be_visible()
    overflow = page.evaluate("""() => {
        const d = document.documentElement, b = document.body;
        const clipped = el => ['hidden', 'clip'].includes(getComputedStyle(el).overflowX);
        return (clipped(d) || clipped(b)) ? 0 : d.scrollWidth - d.clientWidth;
    }""")
    assert overflow <= 2, f"Page is {overflow}px wider than a 375px phone screen (horizontal scrolling)"


def test_no_critical_console_errors(page: Page, base_url: str):
    """Verify the homepage throws no uncaught JavaScript exceptions."""
    errors = []
    page.on("pageerror", lambda err: errors.append(str(err)))
    page.goto(base_url)
    page.wait_for_timeout(1000)
    assert not errors, f"Page threw uncaught exceptions: {errors}"
'''
    ctx.write_test("e2e", "test_navigation.py", code)


# ---------------------------------------------------------------------------
# test_components.py
# ---------------------------------------------------------------------------
def write_components(ctx: SuiteContext) -> None:
    comp = ctx.scan["components"]
    parts = []
    namer = UniqueNamer()

    for card in comp.get("all_cards") or []:
        name = namer(card["type"], "group")
        parts.append(fill('''

def test_repeating_content_items_''' + name + '''(page: Page):
    """Verify a group of repeating content items renders (at least two visible)."""
    page.goto(__URL__)
    items = page.locator(__SEL__)
    expect(items.nth(1)).to_be_visible()
''', URL=card["page_url"], SEL=_visible_variant(card["selector"])))

    search = comp.get("search")
    if search:
        cards_here = next((c for c in comp.get("all_cards") or [] if c["page_url"] == search["page_url"]), None)
        queries = search.get("queries") or [search["sample_query"]]
        body = fill('''

@pytest.mark.parametrize("query", __QUERIES__)
def test_search_input_filtering(page: Page, query: str):
    """Verify the search box accepts a query and a nonsense query does not show more results."""
    page.goto(__URL__)
    box = page.locator(__SEL__).first
    expect(box).to_be_editable()
    box.fill(query)
    expect(box).to_have_value(query)
''', URL=search["page_url"], SEL=search["selector"], QUERIES=queries)
        if cards_here:
            body += fill('''    items = page.locator(__ITEMS__)
    page.wait_for_timeout(800)
    positive = items.count()
    assert positive >= 1, f"Searching for {query!r}, a word from an existing item, shows no items"
    box.fill(__NEG__)
    expect(box).to_have_value(__NEG__)
    page.wait_for_timeout(800)
    assert items.count() <= positive, "Nonsense search query shows more items than a real query"
''', ITEMS=_visible_variant(cards_here["selector"]), NEG=search["negative_query"])
        else:
            body += fill('''    box.fill(__NEG__)
    expect(box).to_have_value(__NEG__)
''', NEG=search["negative_query"])
        parts.append(body)

    for flt in (comp.get("filters") or [])[:8]:
        name = namer(flt["text"], "filter")
        if flt.get("type") == "select":
            parts.append(fill('''

@pytest.mark.parametrize("value", __VALUES__)
def test_filter_dropdown_''' + name + '''(page: Page, value: str):
    """Verify the filter dropdown can be changed to each of its options."""
    errors = []
    page.on("pageerror", lambda err: errors.append(str(err)))
    page.goto(__URL__)
    select = page.locator(__SEL__).first
    expect(select).to_be_visible()
    start_url = page.url
    select.select_option(value)
    page.wait_for_timeout(500)
    assert not errors, f"Choosing {value!r} threw JavaScript errors: {errors}"
    if page.url == start_url:  # some dropdowns submit and reload the page instead
        expect(select).to_have_value(value)
''', URL=flt["page_url"], SEL=flt["selector"], VALUES=flt.get("values") or [flt["sample_value"]]))
        else:
            parts.append(fill('''

def test_filter_control_''' + name + '''(page: Page):
    """Verify the filter button/tab can be clicked without errors and reports its state."""
    errors = []
    page.on("pageerror", lambda err: errors.append(str(err)))
    page.goto(__URL__)
    control = page.locator(__SEL__).filter(has_text=text_re(__TEXT__)).first
    expect(control).to_be_visible()
    start_url = page.url
    control.click()
    page.wait_for_timeout(500)
    assert not errors, f"Clicking the filter threw errors: {errors}"
    if page.url == start_url:
        for attr in ("aria-selected", "aria-pressed"):
            if control.get_attribute(attr) is not None:
                expect(control).to_have_attribute(attr, "true")
                break
''', URL=flt["page_url"], SEL=flt["selector"], TEXT=flt["text"]))

    modal = comp.get("modal")
    if modal:
        trig = modal["trigger"]
        trigger_expr = "page.locator(__TRIG__)"
        if trig.get("text"):
            trigger_expr += '.filter(has_text=text_re(__TTEXT__))'
        body = fill('''

def test_interactive_modal_dialog(page: Page):
    """Verify the dialog opens when its trigger is clicked''' + (" and closes again" if modal.get("close_method") else "") + '''."""
    page.goto(__URL__)
    trigger = ''' + trigger_expr + '''.first
    expect(trigger).to_be_visible()
    trigger.click()
    dialog = page.locator(__DLG__).first
    expect(dialog).to_be_visible()
''', URL=modal["page_url"], TRIG=trig["selector"], TTEXT=trig.get("text") or "", DLG=modal["dialog_selector"])
        if modal.get("close_method") == "button":
            body += fill('''    dialog.locator(__CLOSE__).first.click()
    expect(page.locator(__DLG__)).to_have_count(0)
''', CLOSE=modal["close_selector"], DLG=modal["dialog_selector"])
        elif modal.get("close_method") == "escape":
            body += fill('''    page.keyboard.press("Escape")
    expect(page.locator(__DLG__)).to_have_count(0)
''', DLG=modal["dialog_selector"])
        parts.append(body)

    tables = comp.get("tables") or []
    if tables:
        tbl = tables[0]
        body = fill('''

def test_data_table_rendered(page: Page):
    """Verify the data table renders with its column headers."""
    page.goto(__URL__)
    table = page.locator(__SEL__).first
    expect(table).to_be_visible()
''', URL=tbl["page_url"], SEL=_visible_variant(TABLE_SELECTOR))
        if tbl.get("headers"):
            body += fill('''    expect(table).to_contain_text(__H__)
''', H=tbl["headers"][0])
        parts.append(body)

    if not parts:
        return
    code = header("Components discovered on the site: repeating items, search, filters, dialogs, tables.",
                  ctx, PAGE_IMPORTS, "pytest.mark.e2e")
    ctx.write_test("e2e", "test_components.py", code + "".join(parts))


# ---------------------------------------------------------------------------
# test_forms.py
# ---------------------------------------------------------------------------
def _modal_trigger_expr(modal: dict) -> str:
    """Python source (with __TRIG__/__TTEXT__ placeholders) that finds the element opening the modal."""
    expr = "page.locator(__TRIG__)"
    if modal["trigger"].get("text"):
        expr += '.filter(has_text=text_re(__TTEXT__))'
    return expr


def write_forms(ctx: SuiteContext) -> None:
    forms = ctx.scan["components"].get("forms") or []
    modal = ctx.scan["components"].get("modal") or {}
    modal_form = modal.get("form")
    if not forms and not modal_form:
        return
    doc = ("Non-login forms, on the page and inside popup dialogs: every field is filled and checked, then the form "
           "is SUBMITTED and the page's response is checked (--submit-forms)."
           if ctx.submit_forms else
           "Non-login forms, on the page and inside popup dialogs: every field is filled and checked. "
           "Forms are NOT submitted (regenerate with --submit-forms to submit them).")
    code = header(doc, ctx, PAGE_IMPORTS + "\n\nfrom qa_forms import (SUBMIT_BUTTON, check_empty_submit, check_valid_submit,\n"
                  "                      fill_form, submit_and_observe)", "pytest.mark.e2e")

    for n, frm in enumerate(forms, start=1):
        if not frm.get("fillable_count", frm.get("input_count", 0)):
            continue
        goto = fill('''    page.goto(__URL__)
    form = page.locator("form").nth(__IDX__)
    expect(form).to_be_visible()
''', URL=frm["page_url"], IDX=frm["index"])
        code += _form_tests(f"group_{n}", goto, frm, ctx.submit_forms)

    if modal_form and modal_form.get("fillable_count"):
        goto = fill('''    page.goto(__URL__)
    trigger = ''' + _modal_trigger_expr(modal) + '''.first
    expect(trigger).to_be_visible()
    trigger.click()
    form = page.locator(__DLG__).first.locator("form").first
    expect(form).to_be_visible()
''', URL=modal["page_url"], TRIG=modal["trigger"]["selector"], TTEXT=modal["trigger"].get("text") or "",
                    DLG=modal["dialog_selector"])
        code += _form_tests("modal", goto, modal_form, ctx.submit_forms, where="in the popup dialog")
    ctx.write_test("e2e", "test_forms.py", code)


def _form_tests(suffix: str, goto: str, frm: dict, submit: bool, where: str = "",
                fixture: str = "page", name: str = "form") -> str:
    """
    Fill test, and (with --submit-forms) a valid-submit test plus an empty-submit test for required fields.
    `fixture` is the Page fixture the test uses ("page", or "login_user" / "login_admin" for logged-in forms).
    Forms that look destructive or spend money (delete, logout, checkout...) are filled but never submitted.
    """
    loc = f" {where}" if where else ""
    arg = f"{fixture}: Page"
    start = "" if fixture == "page" else f"    page = {fixture}\n"
    code = f'''

def test_{name}_inputs_{suffix}({arg}):
    """Verify every field in the form{loc} accepts input{" and its submit control is shown" if frm.get("has_submit") else ""}."""
{start}''' + goto + '''    assert fill_form(form) > 0, "No field in the form could be filled"
'''
    if frm.get("has_submit"):
        code += '''    expect(form.locator(SUBMIT_BUTTON).first).to_be_visible()
'''
    if not (submit and frm.get("has_submit")):
        return code
    if frm.get("unsafe_submit"):
        return code + f"\n\n# test_{name}_submit_{suffix} not generated: the form looks destructive or spends money (delete, logout, checkout...).\n"
    code += f'''

@pytest.mark.write
def test_{name}_submit_{suffix}({arg}):
    """Verify submitting the filled form{loc} gets a visible response and causes no server or JavaScript error."""
{start}''' + goto + '''    fill_form(form)
    check_valid_submit(submit_and_observe(page, form))
'''
    if frm.get("required_count"):
        code += f'''

@pytest.mark.write
def test_{name}_empty_submit_{suffix}({arg}):
    """Verify the empty form{loc} is refused with a visible error (it has required fields)."""
{start}''' + goto + '''    check_empty_submit(submit_and_observe(page, form))
'''
    return code


def _logged_in_form_tests(ctx: SuiteContext, forms: list, fixture: str, name: str) -> str:
    """Form tests for forms found inside the user or admin area; they run with the logged-in page fixture."""
    code = ""
    for n, frm in enumerate(forms, start=1):
        goto = fill('''    page.goto(__URL__)
    form = page.locator("form").nth(__IDX__)
    expect(form).to_be_visible()
''', URL=frm["page_url"], IDX=frm["index"])
        code += _form_tests(str(n), goto, frm, ctx.submit_forms, where="in the logged-in area", fixture=fixture, name=name)
    return code


def _fillable(forms) -> list:
    return [f for f in forms or [] if f.get("fillable_count", f.get("input_count", 0))]


# ---------------------------------------------------------------------------
# test_user_session.py
# ---------------------------------------------------------------------------
def write_user_session(ctx: SuiteContext) -> None:
    session = ctx.scan.get("user_session")
    if not (ctx.user_acc and session):
        return
    user_forms = _fillable(session.get("forms"))
    code = header("Logged-in standard user: login, account pages, forms, logout.", ctx,
                  AUTH_IMPORTS + (FORM_IMPORTS if user_forms else ""), "[pytest.mark.e2e, pytest.mark.auth]")
    code += fill('''
USER_LANDING = __LANDING__
''', LANDING=ctx.user_target_url)

    code += '''

def test_user_login_success(login_user: Page, login_url: str):
    """Verify the user can log in and the login form goes away."""
    page = login_user
    assert not password_field_visible(page), "Password field still visible after login"
'''
    if not is_login_url(session["post_login_url"], ctx.login_url):
        code += '''    assert not is_login_url(page.url, login_url), f"Still on a login URL after login: {page.url}"
'''

    namer = UniqueNamer()
    pages = [(namer(lk["name"], "page"), lk["url"]) for lk in session.get("sublinks", [])]
    if pages:
        code += fill('''

USER_PAGES = __PAGES__


@pytest.mark.parametrize("url", [p[1] for p in USER_PAGES], ids=[p[0] for p in USER_PAGES])
def test_user_view(login_user: Page, login_url: str, url: str):
    """Verify the logged-in user can open a page without being sent back to login."""
    response = login_user.goto(url)
    assert response is None or response.status < 400, f"{url} returned {response.status}"
    assert not is_login_url(login_user.url, login_url), f"Redirected to login from {url}"
''', PAGES=pages)

    if session.get("has_logout"):
        code += '''

def test_user_logout(login_user: Page, login_url: str):
    """Verify logging out ends the session."""
    page = login_user
    logout = page.locator(LOGOUT_SELECTOR).first
    expect(logout).to_be_visible()
    logout.click()
    page.wait_for_load_state()
    expect(page.locator(LOGOUT_SELECTOR).first).to_be_hidden()
'''
        if ctx.is_protected_target(ctx.user_target_url):
            code += '''    response = page.goto(USER_LANDING)
    assert access_blocked(page.url, response.status if response else None, USER_LANDING, login_url, password_field_visible(page)), \\
        f"Still able to open {USER_LANDING} after logging out"
'''
    code += _logged_in_form_tests(ctx, user_forms, "login_user", "user_form")
    ctx.write_test("e2e", "test_user_session.py", code)


# ---------------------------------------------------------------------------
# test_admin_portal.py
# ---------------------------------------------------------------------------
def write_admin_portal(ctx: SuiteContext) -> None:
    session = ctx.scan.get("admin_session")
    if not (ctx.admin_acc and session):
        return
    admin_forms = _fillable(session.get("forms"))
    code = header("Logged-in administrator: dashboard, admin sub-pages and forms.", ctx,
                  AUTH_IMPORTS + (FORM_IMPORTS if admin_forms else ""), "[pytest.mark.e2e, pytest.mark.auth]")
    code += fill('''
ADMIN_LANDING = __LANDING__


def test_admin_login_and_dashboard(login_admin: Page, login_url: str):
    """Verify the administrator can log in and open the dashboard."""
    page = login_admin
    response = page.goto(ADMIN_LANDING)
    assert response is None or response.status < 400, f"Dashboard returned {response.status}"
    assert not is_login_url(page.url, login_url), "Redirected to login when opening the dashboard"
''', LANDING=ctx.admin_target_url)
    if session.get("has_heading"):
        code += '''    expect(page.locator("h1, h2").first).to_be_visible()
'''

    namer = UniqueNamer()
    pages = [
        (namer(sp["path"].replace("/", "_"), "page"), sp["url"], sp["has_heading"], sp["has_table"])
        for sp in session.get("subpages", [])
        if sp.get("status") is None or sp["status"] < 400
    ]
    if pages:
        code += fill('''

ADMIN_PAGES = __PAGES__


@pytest.mark.parametrize("url, has_heading, has_table", [p[1:] for p in ADMIN_PAGES], ids=[p[0] for p in ADMIN_PAGES])
def test_admin_subpage(login_admin: Page, login_url: str, url: str, has_heading: bool, has_table: bool):
    """Verify an admin page opens for the administrator and shows what the scan saw."""
    page = login_admin
    response = page.goto(url)
    assert response is None or response.status < 400, f"{url} returned {response.status}"
    assert not is_login_url(page.url, login_url), f"Redirected to login from {url}"
    if has_heading:
        expect(page.locator("h1, h2").first).to_be_visible()
    if has_table:
        expect(page.locator("table:visible, [role='table']:visible").first).to_be_visible()
''', PAGES=pages)
    code += _logged_in_form_tests(ctx, admin_forms, "login_admin", "admin_form")
    ctx.write_test("e2e", "test_admin_portal.py", code)


# ---------------------------------------------------------------------------
# test_access_control.py
# ---------------------------------------------------------------------------
def write_access_control(ctx: SuiteContext) -> None:
    tests = []
    # Guard tests use a page the scan saw guests being refused from (login often lands on a public page, e.g. a cart).
    admin_t, user_t = ctx.admin_guard_url, ctx.user_guard_url

    if ctx.user_acc and ctx.is_protected_target(admin_t) and urlparse(admin_t).path != urlparse(ctx.user_target_url or "").path:
        tests.append(fill('''
@pytest.mark.auth
def test_user_privilege_escalation_blocked(login_user: Page, login_url: str):
    """Verify a standard user cannot open the admin area."""
    page = login_user
    target = __T__
    response = page.goto(target)
    status = response.status if response else None
    assert access_blocked(page.url, status, target, login_url, password_field_visible(page)), \\
        f"Standard user reached the admin page {page.url} (HTTP {status})"
''', T=admin_t))

    for role, target in (("user", user_t), ("admin", admin_t)):
        if ctx.is_protected_target(target):
            tests.append(fill('''
def test_unauthenticated_''' + role + '''_access_blocked(page: Page, login_url: str):
    """Verify a guest opening the ''' + role + ''' area is refused or sent to login."""
    target = __T__
    response = page.goto(target)
    status = response.status if response else None
    assert access_blocked(page.url, status, target, login_url, password_field_visible(page)), \\
        f"Guest reached {page.url} (HTTP {status}) without logging in"
''', T=target))

    if tests:
        code = header("Role-based access control: guests and standard users must not reach protected areas.",
                      ctx, AUTH_IMPORTS, "pytest.mark.e2e")
        ctx.write_test("e2e", "test_access_control.py", code + "\n" + "\n".join(tests))

# ---------------------------------------------------------------------------
# test_interactions.py
# ---------------------------------------------------------------------------
def write_interactions(ctx: SuiteContext) -> None:
    """Tabs, accordion / menu toggles, pagination, carousels and file uploads that worked during the scan."""
    found = ctx.scan["components"].get("interactions") or {}
    namer = UniqueNamer()
    parts = []

    for n, tab in enumerate(found.get("tabs", []), start=1):
        body = fill('''

def test_tabs_''' + str(n) + '''(page: Page):
    """Verify clicking each tab selects it''' + (" and shows its panel" if tab["has_controls"] else "") + '''."""
    page.goto(__URL__)
    tabs = page.get_by_role("tablist").nth(__IDX__).get_by_role("tab")
    assert tabs.count() == __COUNT__, "The number of tabs changed"
    for position in range(tabs.count()):
        tab = tabs.nth(position)
        tab.click()
        expect(tab, "Clicking a tab did not select it").to_have_attribute("aria-selected", "true")
''', URL=tab["page_url"], IDX=tab["tablist_index"], COUNT=tab["count"])
        if tab["has_controls"]:
            body += '''        expect(page.locator(f"[id='{tab.get_attribute('aria-controls')}']"), "The tab's panel is not shown").to_be_visible()
'''
        parts.append(body)

    for tog in found.get("toggles", []):
        expr = "page.locator(__SEL__)"
        if tog["text"]:
            expr += '.filter(has_text=text_re(__TEXT__))'
        opens = not tog["starts_open"]
        what = "accordion" if tog["region"] == "accordion" else "menu"
        body = fill('''

def test_toggle_''' + namer(tog["label"], "toggle") + '''(page: Page):
    """Verify clicking the "''' + tog["label"].replace('"', "'") + '''" ''' + what + (" opens it" if opens else " closes it") + '''."""
    page.goto(__URL__)
    toggle = ''' + expr + '''.first
    expect(toggle).to_be_visible()
    toggle.click()
''', URL=tog["page_url"], SEL=tog["selector"], TEXT=tog["text"] or "")
        if tog["kind"] == "summary":
            body += '    details = toggle.locator("xpath=..")\n'
            body += ('    expect(details, "Clicking the toggle did not open it").to_have_attribute("open", "")\n' if opens
                     else '    expect(details, "Clicking the toggle did not close it").not_to_have_attribute("open", "")\n')
        else:
            verb, state = ("open", "true") if opens else ("close", "false")
            body += f'    expect(toggle, "Clicking the toggle did not {verb} it").to_have_attribute("aria-expanded", "{state}")\n'
        parts.append(body)

    for pag in found.get("pagination", []):
        parts.append(fill('''

def test_pagination_next_page(page: Page):
    """Verify the next-page control in the pagination changes the page or its content."""
    page.goto(__URL__)
    pager = page.locator(__CONT__).nth(__IDX__)
    expect(pager).to_be_visible()
    start_url, start_text = page.url, page.locator("body").inner_text()
    pager.locator(__NEXT__).first.click()
    page.wait_for_load_state("domcontentloaded")
    page.wait_for_timeout(800)
    assert page.url.split("#")[0] != start_url.split("#")[0] or page.locator("body").inner_text() != start_text, \\
        "Clicking the next-page control changed nothing"
''', URL=pag["page_url"], CONT=pag["container_selector"], IDX=pag["container_index"], NEXT=pag["next_selector"]))

    for car in found.get("carousels", []):
        parts.append(fill('''

def test_carousel_next_slide(page: Page):
    """Verify the carousel's next button moves to another slide."""
    page.goto(__URL__)
    carousel = page.locator(__CONT__).nth(__IDX__)
    expect(carousel).to_be_visible()
    before = carousel.inner_html()
    carousel.locator(__NEXT__).first.click()
    page.wait_for_timeout(900)
    assert carousel.inner_html() != before, "Clicking next did not change the carousel"
''', URL=car["page_url"], CONT=car["container_selector"], IDX=car["container_index"], NEXT=car["next_selector"]))

    for n, up in enumerate(found.get("uploads", []), start=1):
        parts.append(fill('''

def test_file_upload_''' + str(n) + '''(page: Page):
    """Verify the file upload field accepts a file (nothing is submitted)."""
    page.goto(__URL__)
    field = page.locator("input[type='file']").nth(__IDX__)
    field.set_input_files(upload_payload(__ACCEPT__))
    assert field.evaluate("el => el.files.length") == 1, "The chosen file was not attached to the upload field"
''', URL=up["page_url"], IDX=up["index"], ACCEPT=up["accept"]))

    for box in found.get("inputs", []):
        name = namer(box["label"], "box")
        label = box["label"].replace('"', "'")
        parts.append(fill('''

def test_type_into_''' + name + '''(page: Page):
    """Verify the "''' + label + '''" box accepts typed text."""
    page.goto(__URL__)
    box = page.locator(__SEL__).first
    expect(box).to_be_editable()
    box.fill(__PROBE__)
    expect(box).to_have_value(__PROBE__)
''', URL=box["page_url"], SEL=box["selector"], PROBE=PROBE))
        if box.get("effect") and ctx.submit_forms:   # pressing Enter only when allowed AND the scan saw it do something visible
            shows_text = box["effect"] == "text_appears"
            check = ('    expect(page.get_by_text(__PROBE__).first, "Pressing Enter did not put the text on the page").to_be_visible()\n'
                     if shows_text else
                     '    assert page.url.split("#")[0] != start_url, "Pressing Enter did not change the page address"\n')
            parts.append(fill('''

@pytest.mark.write
def test_type_into_''' + name + '''_and_press_enter(page: Page):
    """Verify typing text in the "''' + label + '''" box and pressing Enter ''' + ("shows the text on the page" if shows_text else "changes the page address") + '''."""
    page.goto(__URL__)
    start_url = page.url.split("#")[0]
    box = page.locator(__SEL__).first
    expect(box).to_be_editable()
    box.fill(__PROBE__)
    box.press("Enter")
''' + check, URL=box["page_url"], SEL=box["selector"], PROBE=PROBE))

    if not parts:
        return
    imports = PAGE_IMPORTS + ("\n\nfrom qa_forms import upload_payload" if found.get("uploads") else "")
    code = header("Interactive widgets found on the site: tabs, accordion / menu toggles, pagination, carousels, "
                  "file uploads. Each one worked during the scan, so it must keep working.",
                  ctx, imports, "pytest.mark.e2e")
    ctx.write_test("e2e", "test_interactions.py", code + "".join(parts))


def sent_to_login(link: dict, login_url: str = None) -> bool:
    """True if the scan saw this link redirect a guest to the login page (so the status seen was the login page's)."""
    final, own = link.get("final_url") or "", link.get("full_url") or ""
    if not final:
        return False
    if login_url and is_login_url(final, login_url) and not is_login_url(own, login_url):
        return True
    return "login" in urlparse(final).path.lower() and "login" not in urlparse(own).path.lower()


def write_accessibility(ctx: SuiteContext) -> None:
    """One test per scanned public page: no NEW critical or serious accessibility problems (existing ones are shown as a warning)."""
    pages = ctx.scan.get("accessibility") or []
    if not pages:
        return
    namer = UniqueNamer()
    rows = [(namer(path_of(p["page_url"]).strip("/").replace("/", "_") or "home", "page"), p["page_url"],
             sorted(v["id"] for v in p["violations"])) for p in pages]
    code = header("Accessibility (axe-core, WCAG 2 A and AA): no NEW critical or serious problems on each scanned page. "
                  "Problems that already existed when the site was scanned are listed as a warning, not a failure.",
                  ctx, PAGE_IMPORTS + "\n\nfrom qa_a11y import describe, serious_violations", "pytest.mark.e2e")
    code += fill('''

PAGES = __PAGES__


@pytest.mark.parametrize("url, known", [p[1:] for p in PAGES], ids=[p[0] for p in PAGES])
def test_accessibility_serious_issues(page: Page, url: str, known: list):
    """Verify the page has no new critical or serious accessibility problems (WCAG 2 A and AA, checked with axe-core)."""
    page.goto(url)
    found = serious_violations(page)
    new = {rule: details for rule, details in found.items() if rule not in known}
    assert not new, "New accessibility problems: " + describe(new)
    if found:
        pytest.skip("WARNING: existing accessibility problems, already there when the site was scanned: " + describe(found))
''', PAGES=rows)
    ctx.write_test("e2e", "test_accessibility.py", code)


def _is_guest_html_page(link: dict) -> bool:
    status, content_type = link.get("status"), link.get("content_type") or ""
    return (status is None or status < 400) and (not content_type or "html" in content_type) and not sent_to_login(link)
