"""Non-test files of a generated suite: config, credentials, runners, README, shared templates."""

import json
import shutil
from pathlib import Path

from qa_generator.generator.context import SuiteContext

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"
COPIED_TEMPLATES = ("conftest.py", "csv_reporter.py", "qa_login.py", "qa_forms.py")

PYTEST_INI = """[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers
markers =
    e2e: End-to-end user interface tests
    api: Backend API and HTTP endpoint tests
    auth: Tests that need a logged-in account (credentials in .env)
    smoke: Fast sanity checks
    write: Tests that send POST/PUT/PATCH/DELETE requests to the site
"""

SUITE_GITIGNORE = """.env
__pycache__/
.pytest_cache/
test-results/
reports/runs/
"""


def write_project_files(ctx: SuiteContext) -> None:
    out = ctx.output_dir
    for name in COPIED_TEMPLATES:
        shutil.copyfile(TEMPLATES_DIR / name, out / name)
    if ctx.scan.get("consent_banner"):   # the tests dismiss the same cookie banner the scan did
        shutil.copyfile(TEMPLATES_DIR / "qa_consent.py", out / "qa_consent.py")
    if ctx.scan.get("accessibility"):   # axe-core (about 550 KB) is only copied into suites that use it
        for name in ("qa_a11y.py", "axe.min.js"):
            shutil.copyfile(TEMPLATES_DIR / name, out / name)

    suite_config = {
        "base_url": ctx.target_url,
        "target_display": ctx.scan.get("homepage", {}).get("title") or ctx.target_url,
        "login_url": ctx.login_url,
        "is_inertia": ctx.is_inertia,
        "inertia_version": ctx.scan.get("inertia_version", ""),
        "user_target_url": ctx.user_target_url,
        "admin_target_url": ctx.admin_target_url,
        "coverage_notes": [n["text"] for n in ctx.scan.get("coverage_notes") or []],
        "consent_banner": ctx.scan.get("consent_banner"),
    }
    (out / "suite_config.json").write_text(json.dumps(suite_config, indent=2), encoding="utf-8")
    (out / "scan.json").write_text(json.dumps(ctx.scan, indent=2, default=str), encoding="utf-8")
    (out / "pytest.ini").write_text(PYTEST_INI, encoding="utf-8")
    (out / ".gitignore").write_text(SUITE_GITIGNORE, encoding="utf-8")
    _write_env(ctx)

    (out / "run.bat").write_text("@echo off\ncd /d \"%~dp0\"\npytest %*\npause\n", encoding="utf-8")
    (out / "run_live.bat").write_text("@echo off\ncd /d \"%~dp0\"\npytest --headed %*\npause\n", encoding="utf-8")
    (out / "run_api.bat").write_text("@echo off\ncd /d \"%~dp0\"\npytest -m api %*\npause\n", encoding="utf-8")
    (out / "open_report.bat").write_text("@echo off\nstart \"\" \"%~dp0reports\\index.html\"\n", encoding="utf-8")
    (out / "README.md").write_text(_readme(ctx), encoding="utf-8")


def _write_env(ctx: SuiteContext) -> None:
    """Store credentials in a git-ignored .env, merged with any values already there."""
    env_path = ctx.output_dir / ".env"
    values = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, value = line.split("=", 1)
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
                    value = value[1:-1]
                values[key.strip()] = value
    for acc, role in ((ctx.user_acc, "USER"), (ctx.admin_acc, "ADMIN")):
        if acc:
            values[f"QA_{role}_USERNAME"] = acc["username"]
            values[f"QA_{role}_PASSWORD"] = acc["password"]
    if not values:
        return
    lines = ["# Test account credentials. Keep this file out of version control."]
    # Always wrapped in one pair of quotes; conftest strips exactly one pair.
    lines += [f'{k}="{v}"' for k, v in values.items()]
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _coverage_section(ctx: SuiteContext) -> str:
    """What the scan saw but could not test, so a green run is not mistaken for full coverage."""
    notes = ctx.scan.get("coverage_notes") or []
    if not notes:
        return ""
    lines = "\n".join(f"- {n['text']}" for n in notes)
    return f"\n## Not covered by these tests\nThe scan saw the following but the generated tests cannot cover it:\n{lines}\n"


def _readme(ctx: SuiteContext) -> str:
    return f"""# Test Suite for {ctx.target_url}

Generated by **Nes-Dev QA** from a live scan of the site. Tests assert what the
scan actually found, so a missing element or a broken page is reported as a failure.
{_coverage_section(ctx)}
## Setup
```bash
pip install pytest pytest-playwright
playwright install chromium
```
Credentials (if any) are read from `.env` — never commit that file:
```
QA_USER_USERNAME="user@example.com"
QA_USER_PASSWORD="..."
QA_ADMIN_USERNAME="admin@example.com"
QA_ADMIN_PASSWORD="..."
```
Tests that need an account are skipped when its credentials are missing.

## Running tests
- `run.bat` — all tests (headless)
- `run_live.bat` — with a visible browser
- `run_api.bat` — API / HTTP tests only
- `open_report.bat` — open the HTML report

```bash
pytest              # everything
pytest -m e2e       # browser tests
pytest -m api       # HTTP tests
pytest -m auth      # tests that log in
pytest --headed     # watch the browser
```

## Files
- `suite_config.json` — base URL, login URL and scan facts used by the fixtures
- `conftest.py` — fixtures (pages, logged-in pages, HTTP clients) and report hooks
- `qa_login.py` — login helper shared with the generator
- `qa_forms.py` — fills forms, submits them and checks what the page did
- `qa_consent.py` — dismisses the cookie banner the scan found (only in suites for sites that have one)
- `qa_a11y.py` + `axe.min.js` — accessibility checks with axe-core (only in suites that have accessibility tests)
- `csv_reporter.py` — writes `reports/` (CSV, comparison matrix, `index.html`)
- `reports/evidence/` — a screenshot and a Playwright trace of every failed test (shown in `index.html`). Replay a trace with `playwright show-trace reports/evidence/<test id>/trace.zip`; set `NESQA_TRACE=0` to skip traces
- `tests/e2e`, `tests/api` — the generated tests
"""
